# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 612fed37ae21aadf2043983be0f797082fa36daf4d2ba7425863dc33b4c2d05fcb95f6dc08991c57788647080885d49f242c44081b734685b0c6fa95c0c98008

test:
  secret_key_base: b1cd93fcbdf276584ce6d7db2fef702d871cfc73701f7c7f879ca9817ebebae42b2c73e97f5a627ae7f147b11e0a4ace72139dc256ac5c35e7c92497a6cfa248

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
